# Generated by Django 4.1.3 on 2023-01-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('advert_left_img', models.ImageField(default='skyscraper.png', upload_to='static/images/ads')),
                ('advert_right_img', models.ImageField(default='skyscraper.png', upload_to='static/images/ads')),
            ],
        ),
    ]
